---
title: "KNN Classification"
author: "Siddharth.S.Chandran (18BCE1003)"
date: "04/04/2021"
output:
  pdf_document: default
  html_document: default
---

Dataset => Cancer cell dataset

K-NN is a clustering algorithm used to find features in data that are related in natural or
hard to understand ways. K-NN is great for finding 'groups' in data and classifying them.


```{r}
data <- read.csv("C:/Users/Siddharth.S.Chandran/Downloads/data.csv", header=TRUE)
head(data)
```

```{r}
#drop id, can lead to prediction errors if we forget about it
data <- data[-1]
#we care mostly about the diagnosis variable, which is the dependent variable in our model
table(data$diagnosis)
```

```{r}
#Also make the variable more informative
data$diagnosis <- factor(data$diagnosis, levels = c('B','M'), 
                         labels = c('Benign', 'Malignant'))
#look at proportions
round(prop.table(table(data$diagnosis)) * 100, digits = 1)
```
```{r}
#See how the values will react to KNN
summary(data[c('radius_mean','area_mean','smoothness_mean')])
#Clearly the values will need to be normalized
```

```{r}
#Normalize the values with Min-Max
#This is a way of making every value in between 0 and 1, so each observation effects the
#classifier in the same way
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}
#Test out the function
normalize(c(1,2,3,4,5))
normalize(c(10,20,30,40,50))
```

```{r}
#Use lapply to normalize each column in the df
data_n <- as.data.frame(lapply(data[2:31], normalize))
summary(data_n[c('radius_mean','area_mean','smoothness_mean')])
```

```{r}
#Lets try some prediction
library(caret)
data_train <- data_n[1:469,]
data_test <- data_n[470:569,]
#Need to give labels to the new sets
data_train_labels <- data[1:469,1]
data_test_labels <- data[470:569,1]
```

```{r}
#KNN implementation

#The K parameter decides how many neighbors we'd like to consider the distances of when
#implementing the classifier. We typically use K=21 b/c sqrt(459) which is the number
#of observations
library(class)
data_test_pred <- knn(train=data_train, test=data_test,
                      cl=data_train_labels, k=21)
```

```{r}
#Evaluate the algorithm
conf_matrix <- table(data_test_labels, data_test_pred)
conf_matrix
```

```{r}
performance <- sum(diag(conf_matrix)) / sum(conf_matrix)
performance
#Incredible performance
```

